import type { Metadata } from "next";
import "@/styles/globals.scss";
import { childrenProps } from "@/types";

export const metadata: Metadata = {
  title: "ZomatoGram",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: childrenProps) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
